//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:16:47 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http:SpringWebServices.webServices.com/course", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webservices.springwebservices.course;
